# FUNDING.yml
github:
  sponsors:
    - infocliq
    - K-avin

patreon: username
ko-fi: username
open_collective: organization-name
custom:
  - platform: custom-platform
    url: https://infocliq.net
